---
- name: add repository keys
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: 'ACCAF35C'

- name: Add source repository
  apt_repository:
    repo: deb http://apt.insynchq.com/ubuntu {{ ubuntu_version }} non-free contrib
    state: present

- name: Install Insync
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - insync

- name: Delete .ssh folder before creating a symlink
  file:
    state: absent
    path: "~/.ssh/"
  ignore_errors: yes

- name: Create Folder Symlinks
  file:
    src: "~/{{insync_folder}}/{{item}}"
    dest: "~/{{item}}"
    force: yes
    state: link
  with_items:
    - Desktop
    - Pictures
    - Documents
    - Music
    - Videos
    - .ssh
    - .openvpn

- name: remove unused folders
  file:
    path: "~/{{item}}"
    state: absent
  with_items:
    - Templates
    - Public

