---
- name: add repository keys from ubuntu ppa 
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: 'ACCAF35C'

- name: Add source repository
  apt_repository:
    repo: deb http://apt.insynchq.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} non-free contrib
    state: present

- name: Install Insync
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - insync

