---
- name: add repository keys
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 'ACCAF35C'

- name: Add source repository
  apt_repository:
    repo: deb http://apt.insync.io/ubuntu {{ ubuntu_version }} non-free contrib
    state: present

- name: Install Insync
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - insync

- name: Create Folder Symlinks
  file:
    src: "/home/{{username}}/{{insync_folder}}/{{item}}"
    dest: "/home/{{username}}/{{item}}"
    force: yes
    state: link
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755
  with_items:
    - Desktop
    - Documents
    - Videos
    - Pictures
    - .ssh
    - .openvpn

- name: remove unused folders
  file:
    path: "/home/{{username}}/{{item}}"
    state: absent
  with_items:
    - Templates
    - Public
    - Music


