---
- name: Install Insync
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  become_user: "{{username}}"
  with_items:
    - insync-nemo