---

- hosts: all
  vars:
    username: lukas
    git_user: "Lukas Pour"
    git_email: "lukaspour@gmail.com"
    insync_folder: "lukaspour@gmail.com"
  roles:
    - {role: 'common', tags: 'common', 'all'}
    - {role: 'mate', tags: 'mate', 'all'}
    - {role: 'docker', tags: 'docker', 'all'}
    - {role: 'slack', tags: 'slack', 'all'}
    - {role: 'insync', tags: 'insync', 'all'}
    - {role: 'laptop', tags: 'laptop', 'all'}
    - {role: 'git', tags: 'git', 'all'}
    - {role: 'spotify', tags: 'spotify', 'all'}
    - {role: 'chrome', tags: 'chrome', 'all'}
    - {role: 'skype', tags: 'skype', 'all'}
    - {role: 'teamviewer', tags: 'teamviewer', 'all'}
    - {role: 'virtualbox', tags: 'virtualbox', 'all'}
    - {role: 'shutter', tags: 'shutter', 'all'}
    - {role: 'vim', tags: 'vim', 'all'}
    - {role: 'kdeconnect', tags: 'kdeconnect', 'all'}
    - {role: 'lastpass', tags: 'lastpass', 'all'}
    - {role: 'terminator', tags: 'terminator', 'all'}
    - {role: 'pycharm', tags: 'pycharm', 'all'}
    - {role: 'wwan', tags: 'wwan', 'all'} # FIX WWAN ON DELL E7440
    - {role: 'openvpn', tags: 'openvpn', 'all'}
