---
- name: Set MATE Tweak layout
  copy:
    src: "{{ role_path }}/files/"
    dest: "/usr/share/mate-panel/layouts/"
    directory_mode: yes
    owner: root
    group: root
    mode: 0664    

- name: Create autostart folder
  file:
    path: ~/.config/autostart
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755 
