---
- name: Add source repository
  apt_repository:
    repo: 'ppa:linrunner/tlp'

- name: Install important utilities
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  with_items:
    - tlp
    - tlp-rdw

- name: Add TLP config
  copy:
    src: "{{ role_path }}/files/tlp"
    dest: "/etc/default/tlp"
    owner: root
    group: root
    mode: 0644

