---
- name: Add source repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/linrunner/tlp/ubuntu xenial main 
    state: present

- name: Remove conflicting packages
  apt:
    pkg="{{item}}"
    state=absent
    update_cache=true
    purge=yes
    autoremove=yes
  become: true
  with_items:
    - laptop-mode-tools

- name: Install important utilities
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  with_items:
    - tlp
    - tlp-rdw
    - powertop
    - smartmontools

- name: Add TLP config
  copy:
    src: "{{ role_path }}/files/tlp"
    dest: "/etc/default/tlp"
    owner: root
    group: root
    mode: 0644

