---
- name: Install Package
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - shutter
    - libgoocanvas-common

- name: Setup autostart
  copy:
    src: "{{ role_path }}/files/shutter.desktop"
    dest: "~/.config/autostart/shutter.desktop"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

