---
- name: Add Shutter source repository
  apt_repository:
    repo: 'ppa:linuxuprising/shutter'
    codename: "{{ubuntu_version}}"

- name: Install Package
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  with_items:
    - shutter

- name: Setup autostart
  copy:
    src: "{{ role_path }}/files/shutter.desktop"
    dest: "~/.config/autostart/shutter.desktop"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644
  become: yes
  become_user: "{{username}}"


