---
- name: Install required packages
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  with_items:
    - libqmi-utils

- name: Add UDEV rule config
  copy:
    src: "{{ role_path }}/files/99-dell5570.rules"
    dest: "/etc/udev/rules.d/99-dell5570.rules"
    owner: root
    group: root
    mode: 0644

