---
- name: Install git
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - git

- git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"
  become: true
  become_user: "{{username}}"

- git_config:
    name: user.name
    scope: global
    value: "{{git_user}}"
  become: true
  become_user: "{{username}}"

- git_config:
    name: push.default
    scope: global
    value: simple
  become: true
  become_user: "{{username}}"

- name: git clone git prompt
  git:
    repo: git://github.com/jimeh/git-aware-prompt.git
    dest: ~/.bash
    clone: yes
  become: true
  become_user: "{{username}}"

- name: setup .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      export GITAWAREPROMPT=~/.bash
      source "${GITAWAREPROMPT}/main.sh"
      export PS1="\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755

