---
- name: Install git
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - git

- git_config:
    name: user.email
    scope: global
    value: "{{git_email}}"

- git_config:
    name: user.name
    scope: global
    value: "{{git_user}}"

- git_config:
    name: push.default
    scope: global
    value: simple

- name: git clone git prompt
  git:
    repo: git://github.com/jimeh/git-aware-prompt.git
    dest: ~/.bash
    clone: yes
  become: false

- name: setup .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      export GITAWAREPROMPT=~/.bash
      source "${GITAWAREPROMPT}/main.sh"
      export PS1="\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

- name: create directory .git/hooks
  file:
    path: ~/.git/hooks
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755
    recurse: yes

- name: Setup git commit-msg hook
  copy:
    src: "{{ role_path }}/files/commit-msg"
    dest: "~/.git/hooks/commit-msg"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755

- name: Setup git pre-commit hook
  copy:
    src: "{{ role_path }}/files/pre-commit"
    dest: "~/.git/hooks/pre-commit"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755

