---
- name: check if package is already installed
  command: dpkg-query -W slack*
  register: check
  failed_when: false
  changed_when: false

- name: Install slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.8.1-amd64.deb
    state: present
  when: check.rc == 1
  become: true

- name: Setup autostart
  copy:
    src: "{{ role_path }}/files/slack.desktop"
    dest: "~/.config/autostart-scripts/slack.desktop"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

