---
#- name: Install slack
#  command: snap install slack --classic

- name: Install Slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
    state: present
  ignore_errors: yes


#- name: Setup autostart
#  copy:
#    src: "{{ role_path }}/files/slack.desktop"
#    dest: "~/.config/autostart/slack.desktop"
#    owner: "{{username}}"
#    group: "{{username}}"
#    mode: 0644

