---
- name: Download install file
  unarchive:
    src: https://lastpass.com/lplinux.tar.bz2
    dest: /tmp
    remote_src: true

- name: install lastpass
  shell: cd /tmp && ./install_lastpass.sh
  become: true
  become_user: "{{username}}"
