---
- name: check if package is already installed
  command: dpkg-query -W google-chrome*
  register: check
  failed_when: false
  changed_when: false

- name: Install Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  when: check.rc ==1 
#  become: true
#  become_user: "{{username}}"

- name: Change permissions
  file:
    path: /home/lukas/.config/google-chrome
    owner: "{{username}}"
    group: "{{username}}"
    recurse: yes
    state: directory
