---
- name: Remove old terminal
  apt:
    pkg="{{item}}"
    state=absent
    update_cache=true
    purge=yes
  with_items:
    - mate-terminal
    - mate-terminal-common

- name: Install needed packages
  apt:
    pkg="{{item}}"
    state=installed
    cache_valid_time=3600
    update_cache=true
  with_items:
    - terminator

- name: Create Terminator config directory
  file: 
    path="~/.config/terminator"
    state=directory
    owner="{{username}}"
    group="{{username}}"
    mode=0755

- name: Create Terminator plugin directory
  file: 
    path="~/.config/terminator/plugins"
    state=directory
    owner="{{username}}"
    group="{{username}}"
    mode=0755

- name: Add custom terminator config
  copy:
    src: "{{ role_path }}/files/config"
    dest: "~/.config/terminator/config"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

- name: Download google search terminator plugin
  get_url:
    url: https://raw.githubusercontent.com/choffee/terminator-plugins/master/searchplugin.py
    dest: "~/.config/terminator/plugins/searchplugin.py"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

- name: Download clone terminator plugin
  get_url:
    url: https://raw.githubusercontent.com/ilgarm/terminator_plugins/master/clone_session.py
    dest: "~/.config/terminator/plugins/clone_session.py"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644
