---
- name: Add TLP source repository
  apt_repository:
    repo: 'ppa:linrunner/tlp'
    codename: "{{ubuntu_version}}"

- name: Remove conflicting packages
  apt:
    pkg="{{item}}"
    state=absent
    update_cache=true
    purge=yes
    autoremove=yes
  become: true
  with_items:
    - laptop-mode-tools
    - thermald

- name: Install important utilities
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  with_items:
    - tlp
    - tlp-rdw
    - acpi-call-dkms
    - tp-smapi-dkms
    - powertop
    - smartmontools
    - ethtool

- name: Add TLP config
  copy:
    src: "{{ role_path }}/files/tlp.conf"
    dest: "/etc/tlp.conf"
    owner: root
    group: root
    mode: 0644

- name: Remove default CPU governor
  command: update-rc.d -f ondemand remove && update-rc.d -f cpufrequtils remove

