---
- name: update all packages to latest version
  apt: 
    upgrade=dist
    update_cache=yes
    cache_valid_time=3600 
    autoremove=yes

- name: Remove useless apps
  apt:
    pkg="{{item}}"
    state=absent
    purge=yes
    autoremove=yes
  become: true
  with_items:
    - iperf
    - aisleriot
    - webbrowser-app
    - pidgin*
    - brasero*
    - mono-*
    - ubuntu-mate-welcome
    - rhythmbox*
    - synapse
    - mintinstall
    - mintupload
    - mintbackup
    - mintnanny
    - mintupdate
    - mintwelcome
    - ubuntu-mate-welcome

- name: Install important utilities
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - aptitude
    - python-jmespath
    - bash-completion
    - build-essential
    - git
    - htop
    - iftop
    - iotop
    - iptraf
    - elinks
    - mc
    - mtr
    # ncdu: ukazatel obsazeneho mista na disku
    - ncdu
    # nethogs: monitors network activity of each process
    - nethogs
    # nload: network monitor which simply shows TX and RX
    - nload
    - nmap
    # ntp: network time protocol
    - ntp
    # openssl: using as secured telnet: openssl s_client ....
    - openssl
    - screen
    # systat: iostat: io monitoring
    - sysstat
    - tcpdump
    - telnet
    - tmux
    - unzip
    - poedit
    - mtpaint
    - gimp
    - filezilla
    - hplip
    - hplip-data
    - preload
    - ubuntu-restricted-extras
    - whois
    - curl
    - guake
    - inkscape
    - python-pip
    # xdotool key XF86Display - set as display shortcut
    - xdotool
    - numlockx
    - vlc
    - libreoffice
    - libreoffice-l10n-cs
    - snapd

- name: Install Linuxbrew
  script: linuxbrew.sh
  become: yes
  become_user: "{{username}}"

- name: Install brew packages
  command: /home/linuxbrew/.linuxbrew/bin/brew install terragrunt terraform pre-commit vaulted
  become: yes
  become_user: "{{username}}"

- name: Create autostart folder
  file:
    path: ~/.config/autostart
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0755

- name: Setup autostart Guake
  copy:
    src: "{{ role_path }}/files/guake.desktop"
    dest: "~/.config/autostart/guake.desktop"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

- name: "Install (AWS) python package."
  pip:
    name: awscli

- name: "Mount options for /"
  mount:
    path: "/"
    src: "UUID={{ ansible_mounts | json_query('[?mount == `/`] | [0].uuid') }}"
    fstype: "ext4"
    opts: "errors=remount-ro,barrier=0"
    state: "present"

- name: Add SSD scheduler config
  copy:
    src: "{{ role_path }}/files/60-ssd-scheduler.rules"
    dest: "/etc/udev/rules.d/60-ssd-scheduler.rules"
    owner: root
    group: root
    mode: 0644

- name: Add custom sysctl config
  copy:
    src: "{{ role_path }}/files/60-sysctl-ansible.conf"
    dest: "/etc/sysctl.d/60-sysctl-ansible.conf"
    owner: root
    group: root
    mode: 0644

- name: replace default grub GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'

- name: Update grub
  command: update-grub2

- name: Enable the key combination Ctrl+Alt+Backspace
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: 'XKBOPTIONS="terminate:ctrl_alt_bksp"'

- name: Enable UFW firewall
  command: ufw enable

- name: setup /tmp as ramdisk
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: rw,nodev,nosuid,size=1024M
    state: mounted

- name: setup /var/tmp as ramdisk
  mount:
    path: /var/tmp
    src: /tmp
    fstype: tmpfs
    opts: rw,nodev,nosuid,size=1024M
    state: mounted

- name: setup blocked websites
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 idnes.cz www.idnes.cz
      127.0.0.1 ihned.cz www.ihned.cz
      127.0.0.1 lidovky.cz www.lidovky.cz
      127.0.0.1 novinky.cz www.novinky.cz
      127.0.0.1 tn.cz www.tn.cz
      127.0.0.1 super.cz www.super.cz

