---
- name: update all packages to latest version
  apt: 
    upgrade=dist
    update_cache=yes
    cache_valid_time=3600 
    autoremove=yes

- name: Remove useless apps
  apt:
    pkg="{{item}}"
    state=absent
    update_cache=true
    purge=yes
    autoremove=yes
  become: true
  with_items:
    - iperf
    - aisleriot
    - webbrowser-app
    - pidgin*
    - brasero*
    - mono-*
    - ubuntu-mate-welcome
    - rhythmbox*
    - synapse

- name: Install important utilities
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - aptitude
    - python-jmespath
    - bash-completion
    - build-essential
    - git
    - htop
    - iftop
    - iotop
    - iptraf
    - elinks
    - mc
    - mtr
    # ncdu: ukazatel obsazeneho mista na disku - moc uzitecne
    - ncdu
    # nethogs: monitors network activity of each process
    - nethogs
    # nload: network monitor which simply shows TX and RX
    - nload
    - nmap
    # ntp: network time protocol
    - ntp
    # openssl: using as secured telnet: openssl s_client ....
    - openssl
    - screen
    # systat: iostat: io monitoring
    - sysstat
    - tcpdump
    - telnet
    - tmux
    - unzip
    - poedit
    - mtpaint
    - gimp
    - filezilla
    - hplip
    - hplip-data
    - preload
    - ubuntu-restricted-extras
    - whois

- name: "Mount options for /"
  mount:
    path: "/"
    src: "UUID={{ ansible_mounts | json_query('[?mount == `/`] | [0].uuid') }}"
    fstype: "ext4"
    opts: "errors=remount-ro,barrier=0"
    state: "present"

- name: Add SSD scheduler config
  copy:
    src: "{{ role_path }}/files/60-ssd-scheduler.rules"
    dest: "/etc/udev/rules.d/60-ssd-scheduler.rules"
    owner: root
    group: root
    mode: 0644

- name: Add custom sysctl config
  copy:
    src: "{{ role_path }}/files/sysctl.local.conf"
    dest: "/etc/sysctl.d/sysctl.local.conf"
    owner: root
    group: root
    mode: 0644

- name: Run trim more often
  command: mv -v /etc/cron.weekly/fstrim /etc/cron.daily
  ignore_errors: yes  

- name: replace default grub GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'

- name: Update grub
  command: update-grub

- name: Enable the key combination Ctrl+Alt+Backspace
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: 'XKBOPTIONS="terminate:ctrl_alt_bksp"'

- name: Enable UFW firewall
  command: ufw enable

- name: setup /tmp as ramdisk
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: rw,nodev,nosuid,size=1024M
    state: mounted

- name: setup /var/tmp as ramdisk
  mount:
    path: /var/tmp
    src: /tmp
    fstype: tmpfs
    opts: rw,nodev,nosuid,size=1024M
    state: mounted
