---
- name: Remove old versions
  apt:
    pkg="{{item}}"
    state=absent
    update_cache=true
    purge=yes
  become: true
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Add repository key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add source repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ docker_repository_name }} stable
    state: present

- name: Install docker
  apt:
    pkg="{{item}}"
    state=latest 
    cache_valid_time=3600 
    update_cache=true
    force=no
  become: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Ensure docker-compose is installed and available
  get_url: 
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install docker-compose bash completion
  get_url: 
    url : https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: '0644'

- name: allow this user to run docker as root
  command: usermod -aG docker {{ username }}
  become: true

- name: Change default docker network
  lineinfile:
    path: /etc/default/docker
    regexp: '^DOCKER_OPTS='
    line: 'DOCKER_OPTS="--bip=172.31.31.1/24"'

- name: Change default docker network - secondary location
  copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: "/etc/docker/daemon.json"

- name: disable docker autostart to save battery
  command: systemctl disable docker.service
  become: true

- name: disable docker autostart to save battery
  command: systemctl disable docker.socket
  become: true

- name: disable docker autostart to save battery
  command: systemctl disable containerd.service
  become: true

- name: allow this user to run docker as root
  command: usermod -aG docker {{ username }}
  become: true
