#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
#
COMMIT_EDITMSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //' | grep -Eo '[0-9]+')
  DESCRIPTION=$(git config branch."$NAME".description)
  if [ -n "$NAME" ]
  then
    echo "#$NAME - $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
    if [ -n "$DESCRIPTION" ]
    then
       echo "" >> $COMMIT_EDITMSG
       echo $DESCRIPTION >> $COMMIT_EDITMSG
    fi
  fi
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi

