#!/bin/bash
#
# Run python codestyle check before pushing.
#

pep8 statusdroid --exclude=migrations,settings

status=$?
if [ $status -ne 0 ]; then
  echo -e "\033[0;31mCodestyle check failed. Fix issues above.\033[0m"
  exit $status
else
  echo -e "\033[0;32mCodestyle check passed.\033[0m"
fi

