---
- name: Install packages
  apt:
    pkg="{{item}}"
    state=latest
    cache_valid_time=3600
    update_cache=true
    force=no
  become: true
  with_items:
    - openvpn
    - network-manager-openvpn-gnome

- name: Add NetworkManager config
  copy:
    src: "{{ role_path }}/files/vpn.lukapo.cz"
    dest: "/etc/NetworkManager/system-connections/vpn.lukapo.cz"
    owner: root
    group: root
    mode: 0600    

- name: Restart Service
  service:
    name: network-manager
    state: restarted

- name: Setup autostart
  copy:
    src: "{{ role_path }}/files/OpenVPN.desktop"
    dest: "~/.config/autostart/OpenVPN.desktop"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0644

